name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs: 
  build_and_publish:
    runs_on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t ahmednizami/hello-docker:latest
      - name: publish
        run: |
          docker push ahmednizami/hello-docker:latest
      